# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 099bd495d1c30d40e5464a7259c4808e84f2efed841b71a9f77c6b75067f275ee2e773869cf18a68ae095f3bd0d16abbd33b2f433453e6d7885622ab90d34380

test:
  secret_key_base: b40e583abe62343f9a9ab7b555cea0d4b7e753fbd1d0107cfa85c55f9bddd5a93b46f5bfd44ffd1b575d807b3302dbca09b0d3c3923fe9e6fbe15f19abd5674c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
